hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}/${model.model_type}_${ue.reg_type}/asap
    subdir: prompt_id_${data.prompt_id}/fold${data.fold}/id${model.id}

model:
    id: ???
    model_type: ???
    model_name_or_path: 'google/electra-base-discriminator'

ue: ???
training: ???
    
data:
    task_name: 'asap'
    prompt_id: 1
    fold: 0
    subsample_perc: 0.0
    max_seq_length: 512
    validation_subsample: 0.0
    validation_seed: 42
    data_path: '/content/drive/MyDrive/GoogleColab/1.AES/ASAP/data'
  
spectralnorm_layer: 'last'
cache_dir: '../workdir/cache/'
output_dir: '../workdir/results/'
seed: fold_${data.fold}
suffix: ''
do_train: True
do_eval: True
do_ue_estimate: True
reset_params: False
repeat: 0

defaults:
  - training: electra_base
  - ue: mc-dpp