cuda_devices: ''
hydra:
  run:
    dir: ${output_dir}
    
config_path: '../configs/run_glue.yaml'
model_series_dir: '../workdir/models/mrpc/electra/'
task_name: ''
question_id: ''
prompt_id: ''
score_id: ''
model_type: '' 
base_model_name: ''
ue_reg: ''
script: 'run_glue.py'
args: ''
seeds: '17'
output_dir: '../workdir/run_glue_for_model_series'